services:
  - type: web
    name: mermaid-diagram-editor
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    disk:
      name: temp-storage
      mountPath: /opt/render/project/src/backend/temp
      sizeGB: 1

